<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmployeeTaskManagement.Business\EmployeeTaskManagement.Business.csproj" />
    <ProjectReference Include="..\EmployeeTaskManagement.DataAccess\EmployeeTaskManagement.DataAccess.csproj" />
  </ItemGroup>

</Project>
