<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EmployeeTaskManagement.Entities\EmployeeTaskManagement.Entities.csproj" />
    <ProjectReference Include="..\EmployeeTaskManagement.Core\EmployeeTaskManagement.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
